#!/bin/bash

screen_present() {
    found=0
    while read present; do
        if [ x"$1" == x"$present" ]; then
            found=1
            break
        fi
    done <<< $(xrandr | grep " conne" | cut -d " " -f 1)
    echo $found
}

if [ "$#" -eq "0" ]; then
    echo "Liste des ecrans disponibles :"
    xrandr | grep "connected" | sed 's/\([A-Z]\+[-]\?[0-9]*\) \(\(dis\)\?connected\).*/\1 (\2)/'
elif [ "$#" -eq "1" ]; then
    OUTPUT="$1"
    if [ $(screen_present $OUTPUT) -eq 1 ]; then
        xrandr --output $OUTPUT --auto
        xrandr | grep " conne" | sed 's/ conne.*//' | while read tosetoff; do
            if [ "$tosetoff" != "$OUTPUT" ]; then
                xrandr --output $tosetoff --off
            fi
        done
    else
        echo "L'écran n'est pas présent."
    fi

elif [ "$#" -ne "2" ]; then
    echo "Usage : ./script\n\tListe les écrans"
    echo "Usage : ./script ecran_interne ecran_externe\n\tConfigure l'affichage des écrans"
    echo "Usage : ./script ecran\n\tConfigure l'affichage de l'écran et éteint les autres"
else
    EXTERNAL_OUTPUT="$2"
    INTERNAL_OUTPUT="$1"

    if [ $(screen_present $EXTERNAL_OUTPUT) -eq 1 -a $(screen_present $INTERNAL_OUTPUT) -eq 1 ]; then
        #xrandr --output $INTERNAL_OUTPUT --crtc 1 --auto --output $EXTERNAL_OUTPUT --auto --right-of $INTERNAL_OUTPUT
        xrandr --output $INTERNAL_OUTPUT --auto --output $EXTERNAL_OUTPUT --auto --right-of $INTERNAL_OUTPUT
        echo "Configuration terminée"
    else
        echo "L'un des deux ecrans n'est pas présent."
    fi
fi
xset -b

