#!/bin/bash

VPN_STATUS=`nmcli -t -f device con show | grep tun`

if [ x"$VPN_STATUS" == x"tun0" ]; then
  echo '<span foreground="#00FF00"></span>'
else
  echo '<span foreground="#FF0000"></span>'
fi
